-- DATABASE
SELECT * FROM GLOBAL_NAME;
SELECT SYS_CONTEXT('userenv','db_name') from dual;
SELECT ORA_DATABASE_NAME FROM DUAL;

-- DATE
SELECT TO_DATE('12-04-2009', 'DD-MM-YYYY')
FROM DUAL;

-- 1) Write a query which will display the customer id, account type 
-- they hold, their account number and bank name.
SELECT CUSTOMER_ID,ACCOUNT_TYPE,ACCOUNT_NO,BANK_NAME,A.IFSC_CODE
FROM ACCOUNT_INFO A, BANK_INFO B
WHERE A.IFSC_CODE = B.IFSC_CODE;

-- 2) Write a query which will display the customer id, account type and the account number of HDFC customers
-- who registered after 12-JAN-2012 and before 04-APR-2012.
SELECT CUSTOMER_ID, ACCOUNT_TYPE, ACCOUNT_NO
FROM ACCOUNT_INFO
WHERE REGISTRATION_DATE BETWEEN '12-JAN-2012' AND '04-APR-2012'
AND IFSC_CODE =
(
SELECT IFSC_CODE 
FROM BANK_INFO
WHERE BANK_NAME='HDFC'
);

-- 3) Write a query which will display the customer id, customer name,
-- account no, account type and bank name
-- where the customers hold the account.
SELECT A.CUSTOMER_ID,ACCOUNT_NO, ACCOUNT_TYPE,CUSTOMER_NAME,BANK_NAME
FROM ACCOUNT_INFO A, customer_personal_info C, BANK_INFO B
WHERE A.CUSTOMER_ID = C. CUSTOMER_ID
AND A.IFSC_CODE = B.IFSC_CODE;

SHOW AUTOCOMMIT;

COMMIT;
SELECT * FROM ACCOUNT_INFO;

SELECT * 
FROM ALL_OBJECTS
WHERE OWNER = 'ROOT';

-- SCHEMA, VIEW
CREATE SCHEMA AUTHORIZATION ROOT
   CREATE TABLE new_product3 
      (ID NUMBER PRIMARY KEY, color VARCHAR2(10) , quantity NUMBER) 
   CREATE VIEW new_product3_view 
      AS SELECT ID,color, quantity FROM new_product3 WHERE color = 'RED' 
   GRANT select ON new_product3_view TO ROOT; 


SELECT * FROM NEW_PRODUCT3;
SELECT * FROM NEW_PRODUCT3_VIEW;
INSERT INTO new_product3_view VALUES(100,'GREEN',12);
INSERT INTO new_product3_view VALUES(200,'RED',12);

-- SEQUENCE
CREATE SEQUENCE CUSTOMERS_SEQ
START WITH 1000
INCREMENT BY 1;

SELECT *
FROM CUSTOMERS;

INSERT INTO CUSTOMERS
VALUES(CUSTOMERS_SEQ.NEXTVAL, 'KISHORE',100); 

SELECT CUSTOMERS_SEQ.CURRVAL
FROM DUAL;

-- SYNONYM
CREATE SYNONYM CLIENTS 
   FOR CUSTOMERS;

SELECT * 
FROM CLIENTS;

UPDATE CUSTOMERS
SET FULL_NAME='CHAINSYS'
WHERE ID=1003;

ALTER TABLE CUSTOMERS
RENAME COLUMN FULL_NAME TO NAME;

DELETE FROM CUSTOMERS;
ALTER TABLE CUSTOMERS
ADD (CONSTRAINT CUSTOMERS_CK CHECK (NAME IN('NARESH','SELVI','JANANI')));

